name: Yiban

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    
    - name: Set ENV
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Yiban
      env:
        YIBAN_NAME: ${{ secrets.YIBAN_NAME }}
        YIBAN_MOBILE: ${{ secrets.YIBAN_MOBILE }}
        YIBAN_PASSWORD: ${{ secrets.YIBAN_PASSWORD }}
        YIBAN_DATA: ${{ secrets.YIBAN_DATA }}
        YIBAN_EXTEND: ${{ secrets.YIBAN_EXTEND }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
      run: |
        python index.py
